import bcrypt from "bcryptjs";

const data = {
	users: [
		{
			name: "John",
			email: "oyefola1@gmail.com",
			password: bcrypt.hashSync("12345"),
			isAdmin: true,
		},
		{
			name: "Jane",
			email: "oyefola11@gmail.com",
			password: bcrypt.hashSync("12345"),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Free Shirt",
			slug: "free-shirt",
			category: "Shirts",
			image: "images/shirt1.jpg",
			rating: 4.5,
			price: 70,
			brand: "Nike",
			numReviews: 10,
			countInStock: 20,
			desc: "A popular shirt",
		},
		{
			name: "Fit Shirt",
			slug: "fit-shirt",
			category: "Shirts",
			image: "images/shirt1.jpg",
			rating: 5.5,
			price: 60,
			brand: "Adidas",
			numReviews: 10,
			countInStock: 20,
			desc: "A popular shirt",
		},
		{
			name: "Slim Shirt",
			slug: "slim-shirt",
			category: "Shirts",
			image: "images/shirt1.jpg",
			rating: 10,
			price: 30,
			brand: "Raymond",
			numReviews: 10,
			countInStock: 20,
			desc: "A popular shirt",
		},
		{
			name: "Golf Pants",
			slug: "golf-pants",
			category: "Pants",
			image: "images/shirt1.jpg",
			rating: 35,
			price: 90,
			brand: "Oliver",
			numReviews: 10,
			countInStock: 20,
			desc: "A popular pants",
		},
		{
			name: "Fit Pants",
			slug: "fit-pants",
			category: "Pants",
			image: "images/shirt1.jpg",
			rating: 7.5,
			price: 100,
			brand: "Zara",
			numReviews: 10,
			countInStock: 20,
			desc: "A popular pants",
		},
		{
			name: "Classic Pants",
			slug: "classic-pants",
			category: "Pants",
			image: "images/shirt1.jpg",
			rating: 7.5,
			price: 100,
			brand: "Zara",
			numReviews: 10,
			countInStock: 20,
			desc: "A popular pants",
		},
	],
};

export default data;
