import bcrypt from "bcryptjs";

const data = {
	users: [
		{
			name: "John",
			email: "oyefola1@gmail.com",
			password: bcrypt.hashSync("12345"),
			isAdmin: true,
		},
		{
			name: "Jane",
			email: "oyefola11@gmail.com",
			password: bcrypt.hashSync("12345"),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "The Lure of Adventure Silver Watch",
			slug: "the-lure-of-adventure-silver-watch",
			category: "Silver",
			image: "images/products/Silver1",
			price: 70,
			oldPrice: 0,
			brand: "BETH MOSES",
			newItem: true,
			desc: "The Lure of Adventure Silver Watch is a stylish and functional timepiece for adventurous individuals. With a durable silver design, it is suitable for outdoor exploration and taking on new challenges.",
		},
		{
			name: "Hector Alcazar Premium Leather Watch",
			slug: "hector-alcazar-premium-leather-watch",
			category: "Leather",
			image: "images/products/Leather1",
			price: 400,
			oldPrice: 0,
			brand: "AKANJI'S COLLECTIONS",
			newItem: true,
			desc: "The Hector Alcazar Premium Leather Watch is the epitome of luxury and versatility. The premium leather strap is soft to the touch and provides all-day comfort, while the sleek stainless steel casing exudes sophistication. The clean and minimalist watch face adds a touch of classic elegance to the overall design. Advanced features such as a reliable quartz movement and water-resistance make this watch suitable for a variety of activities. It's the perfect accessory for individuals who value both style and functionality and want to elevate their look. Whether dressing up for a special event or keeping it casual, the Hector Alcazar Premium Leather Watch is sure to impress.",
		},
		{
			name: "Henry Avery Limited Edition Gold Watch",
			slug: "henry-avery-limited-edition-gold-watch",
			category: "Gold",
			image: "images/products/Gold1",
			price: 150,
			oldPrice: 250,
			brand: "THE WATCH COMPANY",
			newItem: false,
			desc: "The Henry Avery Limited Edition Gold Watch is a rare and exclusive timepiece for the discerning collector. Its golden finish and intricate details make a luxurious statement. The watch is limited in production and features reliable quartz movement, water-resistance, a durable gold casing, and a minimalist, easy-to-read watch face. Perfect for special events, formal occasions, and elevating everyday looks, it's a valuable addition to any collection or wardrobe.",
		},
		{
			name: "The Twelve Towers Luxury Silver Watch",
			slug: "the-twelve-towers-luxury-silver-watch",
			category: "Silver",
			image: "images/products/Silver2",
			price: 270,
			oldPrice: 0,
			brand: "DRAKE'S FORTUNE",
			newItem: false,
			desc: "The Twelve Towers Luxury Silver Watch boasts a sleek silver casing and leather strap, embodying luxury and style. It features a reliable quartz movement, water-resistance, and a minimalist watch face. Ideal for both fashion and function, this watch is a timeless piece that adds sophistication to any outfit. The perfect choice for the fashion-conscious individual.",
		},
		{
			name: "The Brothers Drake Leather Watch",
			slug: "the-brothers-drake-leather-watch",
			category: "Leather",
			image: "images/products/Leather2",
			price: 50,
			oldPrice: 80,
			brand: "DRAKE'S FORTUNE",
			newItem: false,
			desc: "The Brothers Drake Leather Watch is a durable and stylish timepiece. It features a rugged leather strap and stainless steel casing, a clean watch face, and reliable quartz movement. Water-resistant, it's perfect for outdoor adventures or daily wear. Ideal for those who value style and functionality.",
		},
		{
			name: "New Devon Gold Watch",
			slug: "new-devon-gold-watch",
			category: "Gold",
			image: "images/products/Gold2",
			price: 130,
			oldPrice: 0,
			brand: "BETH MOSES",
			newItem: false,
			desc: "The New Devon Gold Watch is a luxurious timepiece with a gleaming gold casing and leather strap. It boasts a classic watch face and a combination of style and functionality. The perfect accessory for those who value sophistication and practicality.",
		},
		{
			name: "Atlantis of the Sands Crystal Silver Watch",
			slug: "atlantis-of-the-sands-crystal-silver-watch",
			category: "Silver",
			image: "images/products/Silver3",
			price: 48,
			oldPrice: 0,
			brand: "DRAKE'S FORTUNE",
			newItem: false,
			desc: "The Atlantis of the Sands Crystal Silver Watch boasts a sleek silver casing and leather strap, embodying luxury and style. It features a reliable quartz movement, water-resistance, and a minimalist watch face. Ideal for both fashion and function, this watch is a timeless piece that adds sophistication to any outfit. The perfect choice for the fashion-conscious individual",
		},
		{
			name: "The Rub' al Khali Leather Watch",
			slug: "the-rub-al-khali-leather-watch",
			category: "Leather",
			image: "images/products/Leather3",
			price: 190,
			oldPrice: 0,
			brand: "RICK ROLL WATCHES",
			newItem: false,
			desc: "The Rub' al Khali Leather Watch is a durable and stylish timepiece. It features a rugged leather strap and stainless steel casing, a clean watch face, and reliable quartz movement. Water-resistant, it's perfect for outdoor adventures or daily wear. Ideal for those who value style and functionality.",
		},
		{
			name: "The Dreamers of the Day Gold Watch",
			slug: "the-dreamers-of-the-day-gold-watch",
			category: "Gold",
			image: "images/products/Gold3",
			price: 385,
			oldPrice: 0,
			brand: "THE WATCH COMPANY",
			newItem: false,
			desc: "The Dreamers of the Day Gold Watch is a rare and exclusive timepiece for the discerning collector. Its golden finish and intricate details make a luxurious statement. The watch is limited in production and features reliable quartz movement, water-resistance, a durable gold casing, and a minimalist, easy-to-read watch face. Perfect for special events, formal occasions, and elevating everyday looks, it's a valuable addition to any collection or wardrobe.",
		},
		{
			name: "Broken Paradise Silver Watch",
			slug: "broken-paradise-silver-watch",
			category: "Silver",
			image: "images/products/Silver1",
			price: 25,
			oldPrice: 0,
			brand: "DRAKE'S FORTUNE",
			newItem: false,
			desc: "Broken Paradise Silver Watch boasts a sleek silver casing and leather strap, embodying luxury and style. It features a reliable quartz movement, water-resistance, and a minimalist watch face. Ideal for both fashion and function, this watch is a timeless piece that adds sophistication to any outfit. The perfect choice for the fashion-conscious individual",
		},
		{
			name: "Avery's Descent Leather Watch",
			slug: "averys-descent-leather-watch",
			category: "Leather",
			image: "images/products/Leather2",
			price: 135,
			oldPrice: 0,
			brand: "RICK ROLL WATCHES",
			newItem: false,
			desc: "Avery's Descent Leather Watch is a durable and stylish timepiece. It features a rugged leather strap and stainless steel casing, a clean watch face, and reliable quartz movement. Water-resistant, it's perfect for outdoor adventures or daily wear. Ideal for those who value style and functionality.",
		},
		{
			name: "The Brother's Keeper Gold Watch",
			slug: "the-brothers-keeper-gold-watch",
			category: "Gold",
			image: "images/products/Gold3",
			price: 615,
			oldPrice: 0,
			brand: "THE WATCH COMPANY",
			newItem: false,
			desc: "The Brother's Keeper Gold Watch is a rare and exclusive timepiece for the discerning collector. Its golden finish and intricate details make a luxurious statement. The watch is limited in production and features reliable quartz movement, water-resistance, a durable gold casing, and a minimalist, easy-to-read watch face. Perfect for special events, formal occasions, and elevating everyday looks, it's a valuable addition to any collection or wardrobe.",
		},
	],
};

export default data;
